/// Arktion – Journal Module
///
/// Tracks series a user has read on EXTERNAL platforms (AniList, NovelUpdates,
/// MangaDex, etc). This is the user's portable on-chain reading identity — it
/// proves their broader engagement with the medium beyond Arktion itself.
///
/// Journal entries can be marked as submitted-as-suggestion, signaling that the
/// user wants the title on Arktion. NestJS uses this flag to feed the acquisition
/// suggestion queue.
///
/// Dynamic field schema inside UserJournal: String (entry_id) → JournalEntry.
/// entry_id is a UUID generated by NestJS, guaranteeing global uniqueness.
module arktion::journal;

use arktion::admin::AdminCap;
use sui::dynamic_field;
use sui::event;
use std::string::String;

// ===== Format type constants =====

// These are kept as documentation for NestJS callers that map format codes.
#[allow(unused_const)]
const FORMAT_NOVEL: u8 = 0;
#[allow(unused_const)]
const FORMAT_MANGA: u8 = 1;
#[allow(unused_const)]
const FORMAT_MANHWA: u8 = 2;
#[allow(unused_const)]
const FORMAT_MANHUA: u8 = 3;
const FORMAT_WEBTOON: u8 = 4;

// ===== Error codes =====

/// format_type is outside the range 0–4.
const EInvalidFormat: u64 = 0;
/// No entry with this entry_id exists in the journal.
const EEntryNotFound: u64 = 1;
/// Caller is not the owner of this journal.
const ENotOwner: u64 = 2;

// ===== Structs =====

/// One per user. Owns all JournalEntry dynamic fields.
public struct UserJournal has key {
    id: UID,
    owner: address,
}

/// Stored as a dynamic field inside UserJournal, keyed by entry_id.
public struct JournalEntry has store {
    entry_id: String,
    external_title: String,
    format_type: u8,
    external_url: String,
    total_chapters: u64,
    current_chapter: u64,
    notes: String,
    submitted_as_suggestion: bool,
    created_at: u64,
}

// ===== Events =====

public struct EntryAdded has copy, drop {
    owner: address,
    entry_id: String,
    title: String,
}

public struct EntryUpdated has copy, drop {
    owner: address,
    entry_id: String,
}

public struct EntrySubmitted has copy, drop {
    owner: address,
    entry_id: String,
}

// ===== Write functions =====

// ===== Test helpers =====

/// Returns whether the entry has been submitted as a suggestion.
/// Used by tests to assert the flag is set without exposing it in the production API.
#[test_only]
public fun submitted_as_suggestion_for_testing(journal: &UserJournal, entry_id: String): bool {
    dynamic_field::borrow<String, JournalEntry>(&journal.id, entry_id).submitted_as_suggestion
}

/// Create a new UserJournal for `recipient`.
/// Called by NestJS the first time a user signs in (alongside create_library).
public fun create_journal(_cap: &AdminCap, recipient: address, ctx: &mut TxContext) {
    let journal = UserJournal {
        id: object::new(ctx),
        owner: recipient,
    };
    transfer::transfer(journal, recipient);
}

/// Add a new external series entry to the journal.
/// Called by the user — they decide what goes in their reading identity.
/// entry_id is a UUID supplied by the client (NestJS generates it in the PTB).
public fun add_entry(
    journal: &mut UserJournal,
    entry_id: String,
    title: String,
    format_type: u8,
    external_url: String,
    total_chapters: u64,
    current_chapter: u64,
    notes: String,
    ctx: &TxContext,
) {
    assert!(ctx.sender() == journal.owner, ENotOwner);
    assert!(format_type <= FORMAT_WEBTOON, EInvalidFormat);

    dynamic_field::add(&mut journal.id, entry_id, JournalEntry {
        entry_id,
        external_title: title,
        format_type,
        external_url,
        total_chapters,
        current_chapter,
        notes,
        submitted_as_suggestion: false,
        created_at: ctx.epoch_timestamp_ms(),
    });

    event::emit(EntryAdded {
        owner: journal.owner,
        entry_id,
        title,
    });
}

/// Update progress and notes for an existing journal entry.
/// Called by the user — they close the book, not someone else.
public fun update_entry(
    journal: &mut UserJournal,
    entry_id: String,
    current_chapter: u64,
    notes: String,
    ctx: &TxContext,
) {
    assert!(ctx.sender() == journal.owner, ENotOwner);
    assert!(dynamic_field::exists(&journal.id, entry_id), EEntryNotFound);

    let entry = dynamic_field::borrow_mut<String, JournalEntry>(&mut journal.id, entry_id);
    entry.current_chapter = current_chapter;
    entry.notes = notes;

    event::emit(EntryUpdated {
        owner: journal.owner,
        entry_id,
    });
}

/// Flag an entry as submitted to the Arktion acquisition suggestion queue.
/// Called by the user — it's their recommendation. Idempotent: calling twice is harmless.
public fun mark_as_submitted(
    journal: &mut UserJournal,
    entry_id: String,
    ctx: &TxContext,
) {
    assert!(ctx.sender() == journal.owner, ENotOwner);
    assert!(dynamic_field::exists(&journal.id, entry_id), EEntryNotFound);

    let entry = dynamic_field::borrow_mut<String, JournalEntry>(&mut journal.id, entry_id);
    entry.submitted_as_suggestion = true;

    event::emit(EntrySubmitted {
        owner: journal.owner,
        entry_id,
    });
}
